services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - '8053:53/tcp'
      - '8053:53/udp'
      - '853:853/tcp'
      - '3000:3000/tcp'
      - '8081:80/tcp'
      - '8443:443/tcp'
